import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by Prisma, not written by hand.
    "src/generated/**",
    // Separate workspaces with their own toolchains. The desktop wrapper is
    // CommonJS by necessity, which this config's rules reject on principle.
    "electron/**",
    "android/**",
  ]),
]);

export default eslintConfig;
